import { PrismaClient, Framework, Frequency, IntegrationType } from '@prisma/client';

const prisma = new PrismaClient();

const controls = [
  // --- CC1: Control Environment (Governance & HR) ---
  {
    framework: Framework.SOC2,
    controlId: 'CC1.1.1',
    title: 'Code of Conduct',
    description: 'The entity maintains a Code of Conduct and Ethics policy that is reviewed annually and signed by all employees.',
    testProcedure: 'Verify that all employees have signed the Code of Conduct within the last 12 months.',
    frequency: Frequency.ANNUAL,
    category: 'Governance',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC1.1.2',
    title: 'Whistleblower Policy',
    description: 'A whistleblower policy allows employees to report incidents anonymously without fear of retaliation.',
    testProcedure: 'Check for the existence of an anonymous reporting channel.',
    frequency: Frequency.ANNUAL,
    category: 'Governance',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC1.2.1',
    title: 'Board Oversight',
    description: 'The Board of Directors meets quarterly to review security, compliance, and privacy risks.',
    testProcedure: 'Review minutes from quarterly board meetings (redacted for confidentiality).',
    frequency: Frequency.QUARTERLY,
    category: 'Governance',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC1.3.1',
    title: 'Organizational Chart',
    description: 'An organizational chart is maintained to define reporting lines and responsibilities.',
    testProcedure: 'Verify the organizational chart is current and available to employees.',
    frequency: Frequency.QUARTERLY,
    category: 'Governance',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC1.3.2',
    title: 'Job Descriptions',
    description: 'Job descriptions clearly define security roles and responsibilities.',
    testProcedure: 'Sample recent hires to ensure job descriptions include security responsibilities.',
    frequency: Frequency.ANNUAL,
    category: 'HR',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC1.4.1',
    title: 'Background Checks',
    description: 'Background checks are performed for all new hires prior to employment.',
    testProcedure: 'Review HR records for a sample of new hires to verify completed background checks.',
    frequency: Frequency.WEEKLY, // Monitoring new hires
    category: 'HR',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC1.4.2',
    title: 'Confidentiality Agreements',
    description: 'All employees and contractors sign NDAs/Confidentiality agreements upon hire.',
    testProcedure: 'Verify signed NDAs for all active employees and contractors.',
    frequency: Frequency.WEEKLY,
    category: 'HR',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC1.5.1',
    title: 'Performance Reviews',
    description: 'Annual performance reviews evaluate employee adherence to security responsibilities.',
    testProcedure: 'Confirm performance reviews are conducted annually.',
    frequency: Frequency.ANNUAL,
    category: 'HR',
  },

  // --- CC2: Communication & Information ---
  {
    framework: Framework.SOC2,
    controlId: 'CC2.1.1',
    title: 'Security Awareness Training',
    description: 'All employees complete security awareness training upon hire and annually thereafter.',
    testProcedure: 'Check training records for 100% completion rate.',
    frequency: Frequency.MONTHLY,
    category: 'HR',
    integrationType: IntegrationType.OKTA, // Assuming LMS integration via Okta later
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC2.2.1',
    title: 'Internal Security Communication',
    description: 'Security updates and policy changes are communicated to employees via Slack or email.',
    testProcedure: 'Verify a dedicated channel exists for security announcements.',
    frequency: Frequency.MONTHLY,
    category: 'Communication',
    integrationType: IntegrationType.SLACK,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC2.3.1',
    title: 'External Vulnerability Disclosure',
    description: 'A process exists for external researchers to report security vulnerabilities.',
    testProcedure: 'Verify presence of security.txt or a disclosure policy on the website.',
    frequency: Frequency.ANNUAL,
    category: 'Communication',
  },

  // --- CC3: Risk Assessment ---
  {
    framework: Framework.SOC2,
    controlId: 'CC3.1.1',
    title: 'Annual Risk Assessment',
    description: 'A formal risk assessment is conducted annually to identify threats and vulnerabilities.',
    testProcedure: 'Review the latest Risk Assessment Report.',
    frequency: Frequency.ANNUAL,
    category: 'Risk',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC3.2.1',
    title: 'Fraud Risk Assessment',
    description: 'The risk assessment specifically considers fraud risks and potential incentives.',
    testProcedure: 'Verify fraud scenarios are included in the risk register.',
    frequency: Frequency.ANNUAL,
    category: 'Risk',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC3.4.1',
    title: 'Change Impact Analysis',
    description: 'Significant changes to infrastructure or applications undergo a risk assessment.',
    testProcedure: 'Review change logs for evidence of risk analysis on major changes.',
    frequency: Frequency.MONTHLY,
    category: 'Risk',
    integrationType: IntegrationType.JIRA,
  },

  // --- CC4: Monitoring Activities ---
  {
    framework: Framework.SOC2,
    controlId: 'CC4.1.1',
    title: 'Vendor Reviews',
    description: 'Critical vendors are reviewed annually for security compliance (SOC 2, ISO 27001).',
    testProcedure: 'Review vendor management logs and collected vendor audits.',
    frequency: Frequency.ANNUAL,
    category: 'Vendor Management',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC4.2.1',
    title: 'Internal Audit',
    description: 'Periodic internal audits are performed to assess control effectiveness.',
    testProcedure: 'Review internal audit reports and remediation of findings.',
    frequency: Frequency.ANNUAL,
    category: 'Monitoring',
  },

  // --- CC5: Control Activities (Policies) ---
  {
    framework: Framework.SOC2,
    controlId: 'CC5.1.1',
    title: 'Information Security Policy',
    description: 'A master InfoSec policy is maintained, reviewed annually, and approved by management.',
    testProcedure: 'Verify the InfoSec policy was reviewed in the last 12 months.',
    frequency: Frequency.ANNUAL,
    category: 'Governance',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC5.2.1',
    title: 'Acceptable Use Policy',
    description: 'An AUP defines acceptable use of company assets and is acknowledged by all users.',
    testProcedure: 'Verify AUP acknowledgement for all active users.',
    frequency: Frequency.ANNUAL,
    category: 'Governance',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC5.3.1',
    title: 'Clean Desk Policy',
    description: 'Policy requires unattended computers to be locked and sensitive documents secured.',
    testProcedure: 'Walkthrough inspection or automated screen lock configuration check.',
    frequency: Frequency.DAILY,
    category: 'Security',
    integrationType: IntegrationType.OKTA, // Device trust policy
  },

  // --- CC6: Logical and Physical Access ---
  {
    framework: Framework.SOC2,
    controlId: 'CC6.1.1',
    title: 'Access Request and Approval',
    description: 'Access to systems is granted only upon documented request and approval.',
    testProcedure: 'Sample Jira tickets for new access requests for approval evidence.',
    frequency: Frequency.WEEKLY,
    category: 'Access Control',
    integrationType: IntegrationType.JIRA,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.1.2',
    title: 'MFA Enforcement (AWS)',
    description: 'Multi-Factor Authentication is enforced for all AWS IAM users.',
    testProcedure: 'Query AWS IAM for users without MFA enabled.',
    frequency: Frequency.DAILY,
    category: 'Access Control',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.1.3',
    title: 'MFA Enforcement (IdP)',
    description: 'MFA is enforced for all users in the Identity Provider (Okta).',
    testProcedure: 'Query Okta policy to ensure MFA is required.',
    frequency: Frequency.DAILY,
    category: 'Access Control',
    integrationType: IntegrationType.OKTA,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.1.4',
    title: 'Password Complexity',
    description: 'Password policies enforce minimum length, complexity, and rotation.',
    testProcedure: 'Verify password policy settings in Okta.',
    frequency: Frequency.DAILY,
    category: 'Access Control',
    integrationType: IntegrationType.OKTA,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.1.5',
    title: 'Privileged Access Review',
    description: 'Access rights for privileged accounts are reviewed quarterly.',
    testProcedure: 'Review quarterly access review documentation/tickets.',
    frequency: Frequency.QUARTERLY,
    category: 'Access Control',
    integrationType: IntegrationType.JIRA,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.2.1',
    title: 'New Hire Provisioning',
    description: 'User accounts are provisioned based on role-based access control (RBAC).',
    testProcedure: 'Compare new hire roles with assigned system permissions.',
    frequency: Frequency.WEEKLY,
    category: 'Access Control',
    integrationType: IntegrationType.OKTA,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.2.2',
    title: 'Termination Procedures',
    description: 'Access is revoked within 24 hours of employee termination.',
    testProcedure: 'Compare termination dates with access revocation logs.',
    frequency: Frequency.WEEKLY,
    category: 'Access Control',
    integrationType: IntegrationType.OKTA,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.3.1',
    title: 'Least Privilege Principle',
    description: 'Access is restricted to the minimum necessary for the role.',
    testProcedure: 'Review permissions for a sample of users.',
    frequency: Frequency.QUARTERLY,
    category: 'Access Control',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.4.1',
    title: 'Physical Office Security',
    description: 'Physical access to the office is restricted to badged employees and guests.',
    testProcedure: 'Review visitor logs and badge access reports.',
    frequency: Frequency.QUARTERLY,
    category: 'Physical Security',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.4.2',
    title: 'Data Center Security',
    description: 'Physical security of data centers is managed by the cloud provider (AWS).',
    testProcedure: 'Review AWS SOC 2 report for physical security controls.',
    frequency: Frequency.ANNUAL,
    category: 'Physical Security',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.6.1',
    title: 'WAF Configuration',
    description: 'A Web Application Firewall (WAF) protects public-facing endpoints.',
    testProcedure: 'Verify WAF rules and active status.',
    frequency: Frequency.DAILY,
    category: 'Network Security',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.6.2',
    title: 'Network Segmentation',
    description: 'Production and non-production networks are segregated.',
    testProcedure: 'Verify VPC peering and security group rules preventing cross-talk.',
    frequency: Frequency.MONTHLY,
    category: 'Network Security',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.6.3',
    title: 'Remote Access (VPN)',
    description: 'Remote access to internal networks requires VPN/Zero Trust access.',
    testProcedure: 'Verify VPN/Zero Trust configuration and user assignment.',
    frequency: Frequency.DAILY,
    category: 'Network Security',
    integrationType: IntegrationType.OKTA,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.7.1',
    title: 'S3 Encryption',
    description: 'All S3 buckets are encrypted at rest.',
    testProcedure: 'Audit S3 buckets for server-side encryption.',
    frequency: Frequency.DAILY,
    category: 'Data Security',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.7.2',
    title: 'Database Encryption',
    description: 'Databases are encrypted at rest.',
    testProcedure: 'Verify RDS instances have storage encryption enabled.',
    frequency: Frequency.DAILY,
    category: 'Data Security',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.7.3',
    title: 'Encryption in Transit',
    description: 'Data in transit is encrypted using TLS 1.2+.',
    testProcedure: 'Verify Load Balancer SSL policies.',
    frequency: Frequency.DAILY,
    category: 'Data Security',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC6.8.1',
    title: 'Malware Protection',
    description: 'Antivirus/Anti-malware software is installed on all workstations.',
    testProcedure: 'Query device management to confirm AV status.',
    frequency: Frequency.WEEKLY,
    category: 'Workstation Security',
  },

  // --- CC7: System Operations ---
  {
    framework: Framework.SOC2,
    controlId: 'CC7.1.1',
    title: 'Configuration Management',
    description: 'Infrastructure is managed as code (Terraform/CloudFormation).',
    testProcedure: 'Verify infrastructure changes are made via PRs to IaC repos.',
    frequency: Frequency.WEEKLY,
    category: 'DevOps',
    integrationType: IntegrationType.GITHUB,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC7.1.2',
    title: 'Production State Monitoring',
    description: 'Drift detection monitors for unauthorized manual changes.',
    testProcedure: 'Check alerts for configuration drift.',
    frequency: Frequency.DAILY,
    category: 'DevOps',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC7.2.1',
    title: 'Vulnerability Management (Code)',
    description: 'Static analysis (SAST) checks for vulnerabilities in code.',
    testProcedure: 'Verify SAST tools run on every PR.',
    frequency: Frequency.DAILY,
    category: 'Vulnerability Management',
    integrationType: IntegrationType.GITHUB,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC7.2.2',
    title: 'Vulnerability Management (Deps)',
    description: 'SCA tools check for vulnerable dependencies (e.g., Dependabot).',
    testProcedure: 'Verify Dependabot is enabled and alerts are addressed.',
    frequency: Frequency.WEEKLY,
    category: 'Vulnerability Management',
    integrationType: IntegrationType.GITHUB,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC7.2.3',
    title: 'CloudTrail Logging',
    description: 'CloudTrail is enabled for all regions and logs are preserved.',
    testProcedure: 'Verify CloudTrail status.',
    frequency: Frequency.DAILY,
    category: 'Logging',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC7.2.4',
    title: 'Centralized Logging',
    description: 'Logs are aggregated to a central system for analysis.',
    testProcedure: 'Verify logs flow to central logging (CloudWatch/DataDog).',
    frequency: Frequency.DAILY,
    category: 'Logging',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC7.3.1',
    title: 'Incident Response Plan',
    description: 'An incident response plan is maintained and tested annually.',
    testProcedure: 'Verify IRP document and record of last tabletop exercise.',
    frequency: Frequency.ANNUAL,
    category: 'Incident Response',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC7.3.2',
    title: 'Security Alerting',
    description: 'Security alerts are sent to the proper channels for triage.',
    testProcedure: 'Simulate an alert and verify delivery to Slack.',
    frequency: Frequency.DAILY,
    category: 'Incident Response',
    integrationType: IntegrationType.SLACK,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC7.4.1',
    title: 'Business Continuity Plan',
    description: 'A BCP outlines procedures for maintaining operations during disruptions.',
    testProcedure: 'Review BCP and test records.',
    frequency: Frequency.ANNUAL,
    category: 'Business Continuity',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC7.5.1',
    title: 'Disaster Recovery Plan',
    description: 'A DRP covers data restoration and system recovery.',
    testProcedure: 'Review DRP and backup restoration test results.',
    frequency: Frequency.ANNUAL,
    category: 'Business Continuity',
  },

  // --- CC8: Change Management ---
  {
    framework: Framework.SOC2,
    controlId: 'CC8.1.1',
    title: 'Change Management Policy',
    description: 'Policy requires all changes to be documented, tested, and approved.',
    testProcedure: 'Verify policy existence and acknowledgement.',
    frequency: Frequency.ANNUAL,
    category: 'Change Management',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC8.1.2',
    title: 'Peer Review',
    description: 'All code changes require peer review before merging.',
    testProcedure: 'Check GitHub branch protection rules for PR review requirement.',
    frequency: Frequency.DAILY,
    category: 'Change Management',
    integrationType: IntegrationType.GITHUB,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC8.1.3',
    title: 'CI/CD Pipeline',
    description: 'Automated tests must pass before code is deployed.',
    testProcedure: 'Verify CI/CD workflow status for recent deployments.',
    frequency: Frequency.DAILY,
    category: 'Change Management',
    integrationType: IntegrationType.GITHUB,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC8.1.4',
    title: 'Separation of Environments',
    description: 'Dev, Staging, and Production environments are separated.',
    testProcedure: 'Verify distinct environments and access controls.',
    frequency: Frequency.MONTHLY,
    category: 'Change Management',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC8.1.5',
    title: 'Emergency Changes',
    description: 'Process exists for emergency hotfixes with retroactive approval.',
    testProcedure: 'Review emergency change logs for proper documentation.',
    frequency: Frequency.MONTHLY,
    category: 'Change Management',
    integrationType: IntegrationType.JIRA,
  },

  // --- CC9: Risk Mitigation (Vendor Mgmt) ---
  {
    framework: Framework.SOC2,
    controlId: 'CC9.1.1',
    title: 'Business Associate Agreements',
    description: 'BAAs or DPAs are signed with vendors handling sensitive data.',
    testProcedure: 'Review signed contracts for critical vendors.',
    frequency: Frequency.ANNUAL,
    category: 'Vendor Management',
  },
  {
    framework: Framework.SOC2,
    controlId: 'CC9.2.1',
    title: 'Vendor Risk Assessment',
    description: 'Risk assessment is performed for new vendors before onboarding.',
    testProcedure: 'Review vendor intake forms and risk scoring.',
    frequency: Frequency.WEEKLY,
    category: 'Vendor Management',
  },

  // --- Availability Criteria (A) ---
  {
    framework: Framework.SOC2,
    controlId: 'A1.1.1',
    title: 'Capacity Planning',
    description: 'System capacity is monitored to ensure availability.',
    testProcedure: 'Review capacity utilization reports.',
    frequency: Frequency.QUARTERLY,
    category: 'Availability',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'A1.2.1',
    title: 'Data Backups',
    description: 'Daily automated backups are performed for production databases.',
    testProcedure: 'Verify backup schedule and success logs in AWS Reports.',
    frequency: Frequency.DAILY,
    category: 'Availability',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'A1.2.2',
    title: 'Backup Restoration Test',
    description: 'Backups are tested for restorability at least annually.',
    testProcedure: 'Review restoration test report.',
    frequency: Frequency.ANNUAL,
    category: 'Availability',
    integrationType: IntegrationType.AWS,
  },
  {
    framework: Framework.SOC2,
    controlId: 'A1.3.1',
    title: 'Redundancy',
    description: 'Critical systems are deployed across multiple Availability Zones.',
    testProcedure: 'Verify Multi-AZ deployment in AWS.',
    frequency: Frequency.MONTHLY,
    category: 'Availability',
    integrationType: IntegrationType.AWS,
  },

  // --- Confidentiality Criteria (C) ---
  {
    framework: Framework.SOC2,
    controlId: 'C1.1.1',
    title: 'Data Classification',
    description: 'Data is classified based on sensitivity (e.g., Public, Internal, Confidential).',
    testProcedure: 'Review Data Classification Policy and data tagging.',
    frequency: Frequency.ANNUAL,
    category: 'Confidentiality',
  },
  {
    framework: Framework.SOC2,
    controlId: 'C1.2.1',
    title: 'Data Retention & Disposal',
    description: 'Data is retained and disposed of according to policy.',
    testProcedure: 'Verify automated deletion of expired data.',
    frequency: Frequency.QUARTERLY,
    category: 'Confidentiality',
    integrationType: IntegrationType.AWS, // S3 Lifecycle rules
  },
  {
    framework: Framework.SOC2,
    controlId: 'C1.2.2',
    title: 'Asset Disposal',
    description: 'Physical assets are sanitized before disposal.',
    testProcedure: 'Review certificates of destruction for retired hardware.',
    frequency: Frequency.ANNUAL,
    category: 'Confidentiality',
  },

  // --- Privacy Criteria (P) ---
  {
    framework: Framework.SOC2,
    controlId: 'P1.1.1',
    title: 'Privacy Notice',
    description: 'Privacy notice is published and kept up to date.',
    testProcedure: 'Verify Privacy Policy on website.',
    frequency: Frequency.ANNUAL,
    category: 'Privacy',
  },
  {
    framework: Framework.SOC2,
    controlId: 'P2.1.1',
    title: 'Data Subject Requests',
    description: 'Process exists to handle DSRs (access, deletion, correction).',
    testProcedure: 'Review log of DSRs and response times.',
    frequency: Frequency.MONTHLY,
    category: 'Privacy',
  },
  {
    framework: Framework.SOC2,
    controlId: 'P3.1.1',
    title: 'Consent Management',
    description: 'Consent is obtained before collecting personal data where required.',
    testProcedure: 'Verify cookie banner and consent logs.',
    frequency: Frequency.MONTHLY,
    category: 'Privacy',
  },
];

async function main() {
  console.log(`Seeding ${controls.length} SOC 2 Controls...`);

  for (const control of controls) {
    const existing = await prisma.control.findUnique({
      where: {
        framework_controlId: {
          framework: control.framework,
          controlId: control.controlId,
        },
      },
    });

    if (!existing) {
      await prisma.control.create({
        data: control,
      });
      console.log(`Created control: ${control.controlId}`);
    } else {
      await prisma.control.update({
        where: { id: existing.id },
        data: control,
      });
      console.log(`Updated control: ${control.controlId}`);
    }
  }

  console.log('Seeding completed.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
